services:
  postgres:
    image: postgis/postgis:14-3.5-alpine
    ports:
      # use different port if running native postgres on your local
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=aroundhome
    volumes:
      - ./sql/master.sql:/docker-entrypoint-initdb.d/0000-master.sql
    # uncomment to load the dump
    # - ./sql/dump.sql://docker-entrypoint-initdb.d/0001-dump.sql

  matcher:
    image: matcher
    ports:
      - 8080:8080
    environment:
      - dbconn=postgres://postgres:pass@postgres/aroundhome?sslmode=disable
      - bind=0.0.0.0:8080
    build: .
